## Ejercicios - Algebra

In [1]:
import numpy as np

import random

In [2]:
# Versiones
print(f"numpy=={np.__version__}")

numpy==2.2.0


In [3]:
var = '01234567'
print(var[::2])

0246


### Ejercicio 1:
- Usando la librería _**random**_, genera una matriz de $4x4$ de números enteros del 1 al 100, usando bucles.
- El resultado debe ser un _**np.array()**_.

In [4]:

matriz = []
for i in range (4):
    filas = []
    for j in range (4):
        filas.append(random.randint(1, 100))
    matriz.append(filas)
matriz = np.array(matriz)
type(matriz)
print(matriz)

[[59 78 15  8]
 [33 81 48 32]
 [ 2 89 65 53]
 [75  7 49 89]]


### Ejercicio 2:

- Define una función que tome como parámetro de entrada 2 valores enteros ($m$, $n$).
- La función debe generar, usando la librería _**random**_, una matriz de $mxn$ de números enteros del 1 al 100, usando bucles.
- La función debe retornar la matriz, la matriz debe ser un _**np.array()**_.

In [7]:
def ejercicio2(n, m):
    matriz = []
    for _ in range(n):
        filas = [random.randint(1, 100) for _ in range (m)]
        matriz.append(filas)
    return np.array(matriz)
    

matriz2 = ejercicio2(5, 7)
print(matriz2)

[[82 38 75 77  9 97 38]
 [38 97 64 51 89 55 79]
 [64  8 20 90 92 54  4]
 [61 81 10 19 32 25 37]
 [67 80 20 68 43 82 13]]


In [5]:
##############################################################################################################################