## Ejercicios - NumPy 1

In [1]:
import numpy as np

In [2]:
# Versión
print(f"numpy=={np.__version__}")

numpy==2.2.0


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [3]:
lista = []
for i in range(20):
    if i % 2 == 0:
        lista.append(i)

np.array(lista)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
lista = []
for i in range(2, 22, 2):
    lista.append(i)

np.array(lista)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
array_pares = np.array([i for i in range(2, 22, 2)])
array_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [6]:
array_pares.ndim

1

In [7]:
# numero de elementos en total
array_pares.size

10

In [8]:
# numero de elementos en cada dimension
array_pares.shape

(10,)

In [9]:
array_pares.dtype

dtype('int64')

In [10]:
array = np.array([10, 10, 20, 20, 30, 30])
array

array([10, 10, 20, 20, 30, 30])

In [11]:
array_acumulado = np.cumsum(array)
array_acumulado

array([ 10,  20,  40,  60,  90, 120])

In [12]:
np.diff(array_acumulado)

array([10, 20, 20, 30, 30])

In [13]:
# agregar el primero manualmente ya que no tiene ninguno delante para obtener el diff
original = np.insert(np.diff(array_acumulado), 0, array_acumulado[0])
original

array([10, 10, 20, 20, 30, 30])

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [14]:
pares = np.array([i for i in range(2, 11, 2)])
pares

array([ 2,  4,  6,  8, 10])

In [15]:
impares = np.array([i for i in range(1, 11, 2)])
impares

array([1, 3, 5, 7, 9])

In [16]:
# concatenate y reshape. Por defecto es axis=0. Como es vector de 1 dimensión, axis 1 da error, no hay dos dimensiones
numbers = np.concatenate((pares, impares))
numbers

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [17]:
matriz_5x2 = numbers.reshape(5, 2)
matriz_5x2


array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [18]:
matriz_5x2.shape

(5, 2)

In [19]:
# lo aplana de 2 dimensiones a una dimensión:
matriz_5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [20]:
np.ravel(matriz_5x2)

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [21]:
# esto interesa si los datos son pareados, y están relacionados,
# Por ejemplo si queremos combinar elemento a elemento de un array city_consumption con road_consumption
np.column_stack((pares, impares))

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

In [22]:
print(pares)
print(np.where(pares > 5))

[ 2  4  6  8 10]
(array([2, 3, 4]),)


In [23]:
indices = np.where(pares > 5) # devuelve los indices de los elementos que cumplen con la condiciones/es
pares[indices] # usamos los indices como filtros

array([ 6,  8, 10])

In [24]:
# en pandas
# filtro = df['price'] > 20
# df[filtro]

### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [25]:
matriz_5x2.dtype

dtype('int64')

### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

In [26]:
# Crear una matriz de ceros de dimensión (4, 4)
matriz = np.zeros((4, 4))

# Reemplazar los elementos de la diagonal principal por el número 5
np.fill_diagonal(matriz, 5)

print(matriz)


[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

In [27]:
# Crear un vector con 10 elementos entre -5 y 5
vector = np.linspace(-5, 5, 10)

print(vector)


[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

In [28]:
# Crear una matriz vacía de tamaño (3, 6) con elementos de tipo flotante
matriz_vacia = np.empty((3, 6), dtype=float)

print(matriz_vacia)
# Al no estatar inicializada, los valores son aleatorios, no son ceros, ni unos, ni nada en particular.


[[1.03327168e-311 2.09338971e-314 0.00000000e+000 0.00000000e+000
  8.34441742e-308 1.16096346e-028]
 [9.82205649e+252 1.11789342e+253 4.29436185e-086 6.98684252e-077
  3.28879940e-086 6.98684252e-077]
 [3.28879940e-086 6.98687546e-077 3.28879940e-086 8.44657431e-053
  2.59305626e-306 1.25160405e-308]]


### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

In [29]:
def es_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def generar_primos(limite):
    primos = []
    num = 2
    while len(primos) < limite:
        if es_primo(num):
            primos.append(num)
        num += 1
    return primos

In [30]:
# Generar una lista de 18 números primos
primos = generar_primos(18)

# Llenar la matriz vacía con los números primos
matriz_vacia = np.array(primos).reshape((3, 6))

print(matriz_vacia)


[[ 2  3  5  7 11 13]
 [17 19 23 29 31 37]
 [41 43 47 53 59 61]]


### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

In [31]:
# Definir la matriz inicial
matriz = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Reemplazar los números en la posición especificada por 99
matriz[0, 2] = 99
matriz[1, 1] = 99
matriz[1, 3] = 99
matriz[2, 0] = 99
matriz[3, 2] = 99

print(matriz)


[[ 1  2 99  4]
 [ 5 99  7 99]
 [99 10 11 12]
 [13 14 99 16]]


### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

In [32]:
# Obtener la primera y tercera fila de la matriz
primera_fila = matriz[0, :]
tercera_fila = matriz[2, :]

print("Primera fila:", primera_fila)
print("Tercera fila:", tercera_fila)


Primera fila: [ 1  2 99  4]
Tercera fila: [99 10 11 12]


### Ejercico 11:
- Obten la tercera columna de la matriz.

In [33]:
# Obtener la tercera columna de la matriz
tercera_columna = matriz[:, 2]

print("Tercera columna:", tercera_columna)


Tercera columna: [99  7 11 99]


### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

In [34]:
# Obtener la segunda y tercera columna de la matriz
segunda_y_tercera_columna = matriz[:, 1:3]

print("Segunda y tercera columna:\n", segunda_y_tercera_columna)


Segunda y tercera columna:
 [[ 2 99]
 [99  7]
 [10 11]
 [14 99]]


### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

In [35]:
# Obtener una submatriz con los 4 números del centro
submatriz_centro = matriz[1:3, 1:3]

print("Submatriz con los 4 números del centro:\n", submatriz_centro)


Submatriz con los 4 números del centro:
 [[99  7]
 [10 11]]


### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

In [36]:
# Aplicar np.flatten() a la submatriz central para obtener un vector
vector = submatriz_centro.flatten()

print("Vector resultante:", vector)


Vector resultante: [99  7 10 11]


### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

In [37]:
# Aplicar el método .reshape() al vector para obtener una matriz de (1, 4)
matriz_reshape = vector.reshape((1, 4))

print("Matriz de dimensiones (1, 4):\n", matriz_reshape)


Matriz de dimensiones (1, 4):
 [[99  7 10 11]]


### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [38]:
# Crear dos matrices de dimensión (4, 4) con números aleatorios
matriz1 = np.random.rand(4, 4)
matriz2 = np.random.rand(4, 4)

# Concatenar las matrices verticalmente
matriz_concatenada = np.vstack((matriz1, matriz2))

print("Matriz 1:\n", matriz1)
print("\nMatriz 2:\n", matriz2)
print("\nMatriz concatenada verticalmente:\n", matriz_concatenada)


Matriz 1:
 [[0.99502646 0.08866958 0.129192   0.76969955]
 [0.3927118  0.9380602  0.49212741 0.01674212]
 [0.18865287 0.10650376 0.14004122 0.63820539]
 [0.35509857 0.00604995 0.0889486  0.92736392]]

Matriz 2:
 [[0.79262728 0.04692098 0.87412982 0.25119025]
 [0.36285551 0.1700525  0.45571942 0.39959862]
 [0.6982981  0.69107084 0.09745566 0.28233596]
 [0.5322408  0.7362217  0.72615751 0.52593311]]

Matriz concatenada verticalmente:
 [[0.99502646 0.08866958 0.129192   0.76969955]
 [0.3927118  0.9380602  0.49212741 0.01674212]
 [0.18865287 0.10650376 0.14004122 0.63820539]
 [0.35509857 0.00604995 0.0889486  0.92736392]
 [0.79262728 0.04692098 0.87412982 0.25119025]
 [0.36285551 0.1700525  0.45571942 0.39959862]
 [0.6982981  0.69107084 0.09745566 0.28233596]
 [0.5322408  0.7362217  0.72615751 0.52593311]]


In [39]:
################################################################################################################################